### ISSUE TITLE
Dont Repeat Your styles

### ISSUE THREAD

**Issue by zannain** [Bastonje/prj-rev-bwfs-tea-cozy#2]
[Dont-Repeat-Yourself](http://deviq.com/don-t-repeat-yourself/). This is one of the most well know programming principles. If you find yourself repeating certain styles this is an indication that you simplify your stylesheet by making use of classes.

For [example](https://github.com/Bastonje/prj-rev-bwfs-tea-cozy/blob/master/TeaCozy/resources/styles/style.css#L12-L20)

```css
h2 {
	margin: 0;
	padding: 10px;
}

h4 {
	margin: 0;
	padding: 10px;
}
```

You could refactor this to be:

```css
h2,
h4 {
    margin: 0;
    padding: 10px;
}
```

Doing more with less code is the mark of an experienced developer. It often means less time to process everything which can mean faster loading times. In fact, one of the main jobs of a senior developer is to find bottlenecks or pieces of code that might be slowing down loading times and refactor them to ensure optimal speed.
